Repository nextcloud/recommendations, pull requests merged in 2019-03, with the labels that each got.

#51 Add Travis config
  .travis.yml
Labels: 3. to review, enhancement, technical debt

#52 Fix CI
  .travis.yml
  package-lock.json
  package.json
Labels: 3. to review, bug, technical debt

#53 Add php linting
  .gitignore
  .travis.yml
  composer.json
Labels: 3. to review, technical debt

#43 Deduplicate recommendations
  lib/Service/RecommendationService.php
Labels: bug

#55 Add border radius to thumbnails like in Files app
  src/components/RecommendedFile.vue
Labels: 4. to release, design, enhancement

#54 Make compatible with Nextcloud 16 only
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Service/IRecommendation.php
  lib/Service/RecommendationService.php
  lib/Service/RecommendedFile.php
Labels: 3. to review, enhancement

#56 Release v0.4.0
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#58 Limit number of rows on mobile
  lib/Service/RecommendationService.php
  src/components/Recommendations.vue
Labels: 3. to review, bug

#62 Commit assets
  .gitignore
  js/main.js
  js/main.js.map
Labels: 3. to review

#60 Fix whitespace showing when no recommendations are available
  .gitattributes
  js/main.js
  js/main.js.map
  lib/Controller/RecommendationController.php
  src/components/Recommendations.vue
Labels: 3. to review, bug, design

#65 Fix recommendations showing in subdirectory
  js/main.js
  js/main.js.map
  src/main.js
Labels: 3. to review, bug
