Repository nextcloud/recommendations, pull requests merged in 2019-12, with the labels that each got.

#158 Add php7.4 support, drop 7.1
  .travis.yml
  appinfo/info.xml
Labels: 3. to review

#156 Fix spacing for thumbnails and recommendations list
  js/main.js
  js/main.js.map
  src/components/Recommendations.vue
  src/components/RecommendedFile.vue
Labels: 4. to release, bug, design

#157 Add note to development setup docs about committing built files
  README.md
Labels: 4. to release, enhancement
