Repository nextcloud/recommendations, pull requests merged in 2019-07, with the labels that each got.

#101 Fix entry width and accessibility
  js/main.js
  js/main.js.map
  src/components/RecommendedFile.vue
Labels: 3. to review, bug, design

#95 Update fstream
  package-lock.json
Labels: 3. to review, security

#110 Revert "Add User Toggle"
  appinfo/info.xml
  appinfo/routes.php
  js/main.js
  js/main.js.map
  js/personal-settings.js
  js/personal-settings.js.map
  lib/Controller/RecommendationController.php
  lib/Controller/SettingsController.php
  lib/Settings/Personal.php
  lib/Settings/PersonalSection.php
  package-lock.json
  src/components/PersonalSettings.vue
  src/personal-settings.js
  src/webpack.common.js
  templates/personal.php
Labels: 3. to review
