Repository nextcloud/recommendations, pull requests merged in 2022-08, with the labels that each got.

#526 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#535 Update and rename dependabot-approve.yml to dependabot-approve-merge.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/dependabot-approve.yml
Labels: 4. to release

#536 Bump minimist from 1.2.5 to 1.2.6
  package-lock.json
  package.json
Labels: 3. to review

#537 Update node workflow for improved error messages
  .github/workflows/node.yml
Labels: 3. to review

#538 Bump lodash from 4.17.19 to 4.17.21
  js/dashboard.js.map
  js/main.js.map
  package-lock.json
  package.json
Labels: 3. to review

#539 Migrate to global packages and update dependencies
  .babelrc
  .stylelintrc.js
  babel.config.js
  js/dashboard.js
  js/dashboard.js.map
  js/files_recommendation-dashboard.js
  js/files_recommendation-dashboard.js.LICENSE.txt
  js/files_recommendation-dashboard.js.map
  js/files_recommendation-main.js
  js/files_recommendation-main.js.LICENSE.txt
  js/files_recommendation-main.js.map
  js/main.js
  js/main.js.map
  lib/Dashboard/RecommendationWidget.php
  lib/Listeners/FilesLoadAdditionalScriptsListener.php
  package-lock.json
  package.json
  src/components/Dashboard.vue
  src/store/store.js
  src/webpack.common.js
  src/webpack.dev.js
  src/webpack.prod.js
  stylelint.config.js
  webpack.config.js
Labels: enhancement, technical debt, 3. to review, dependencies

#542 Fix translation sync
  .l10nignore
Labels: 3. to review
