Repository nextcloud/recommendations, pull requests merged in 2022-01, with the labels that each got.

#465 Update version on master
  appinfo/info.xml
  package.json
Labels: 3. to review

#464 Migrate from node-sass to sass
  js/dashboard.js
  js/dashboard.js.map
  js/main.js
  js/main.js.map
  package-lock.json
  package.json
Labels: technical debt, 3. to review

#469 Create block-merge-freeze.yml
  .github/workflows/block-merge-freeze.yml
Labels: backport-request
