Repository nextcloud/recommendations, pull requests merged in 2023-05, with the labels that each got.

#610 Add npm-audit-fix
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#611 [master] Fix npm audit
  package-lock.json
Labels: 4. to release, dependencies

#612 [stable25] Fix npm audit
  js/files_recommendation-dashboard.js
  js/files_recommendation-dashboard.js.map
  js/files_recommendation-main.js
  js/files_recommendation-main.js.map
  package-lock.json
Labels: 4. to release, dependencies

#613 [stable26] Fix npm audit
  .github/workflows/test.yml
  js/files_recommendation-dashboard.js
  js/files_recommendation-dashboard.js.map
  js/files_recommendation-main.js
  js/files_recommendation-main.js.map
  package-lock.json
Labels: 4. to release, dependencies

#615 [stable24] Fix npm audit
  .github/workflows/test.yml
  js/dashboard.js
  js/dashboard.js.map
  js/main.js
  js/main.js.map
  package-lock.json
Labels: 4. to release, dependencies

#616 [stable24] Fix npm audit
  package-lock.json
Labels: 4. to release, dependencies

#617 chore(CI): Adjust testing matrix for Nextcloud 27 on stable27
  .github/workflows/test.yml
Labels: 4. to release

#618 feat(deps): Add Nextcloud 28 support on master
  appinfo/info.xml
  package.json
Labels: 4. to release

#619 [master] Fix npm audit
  package-lock.json
Labels: 4. to release, dependencies
