Repository nextcloud/recommendations, pull requests merged in 2024-04, with the labels that each got.

#716 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#717 [stable27] Fix npm audit
  .github/workflows/test.yml
  package-lock.json
Labels: 3. to review, dependencies

#667 Revert "perf(dashboard): implement widget item api v2"
  .github/workflows/test.yml
  js/recommendations-dashboard.js
  js/recommendations-dashboard.js.LICENSE.txt
  js/recommendations-dashboard.js.map
  js/recommendations-main.js
  js/recommendations-main.js.map
  lib/Dashboard/RecommendationWidget.php
  package-lock.json
  package.json
  src/components/Dashboard.vue
  src/dashboard.js
  webpack.config.js
Labels: 3. to review

#727 fix: Fix navigation to folder
  js/recommendations-dashboard.js
  js/recommendations-dashboard.js.map
  js/recommendations-main.js
  js/recommendations-main.js.map
  package-lock.json
  package.json
  src/components/RecommendedFile.vue
Labels: 3. to review, backport-request

#729 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#731 [master] Fix npm audit
  .github/workflows/test.yml
  js/recommendations-dashboard.js
  js/recommendations-dashboard.js.map
  package-lock.json
Labels: 3. to review, dependencies

#733 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#734 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies
