Repository nextcloud/recommendations, pull requests merged in 2024-02, with the labels that each got.

#699 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#703 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .gitignore
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Command/GetRecommendations.php
  lib/Controller/RecommendationController.php
  lib/Controller/SettingsController.php
  lib/Service/RecentlyCommentedFilesSource.php
  lib/Service/RecentlyEditedFilesSource.php
  lib/Service/RecentlySharedFilesSource.php
  lib/Service/RecommendationService.php
  lib/Service/RecommendedFile.php
Labels: 3. to review, dependencies, automated

#702 fix: support 28 Files
  js/recommendations-main.js
  js/recommendations-main.js.map
  src/components/RecommendedFile.vue
  src/main.js
Labels: bug, 3. to review, regression
