Repository nextcloud/recommendations, pull requests merged in 2024-07, with the labels that each got.

#766 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#767 fix(dashboard): Fix dashboard icon
  lib/Dashboard/RecommendationWidget.php
Labels: 3. to review

#769 Migrate REUSE to TOML format
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  LICENSES/BSD-3-Clause.txt
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/ISC.txt
  LICENSES/MPL-2.0.txt
  REUSE.toml
  build-js/WebpackSPDXPlugin.js
  build-js/npm-post-build.sh
  js/recommendations-dashboard.js
  js/recommendations-dashboard.js.LICENSE.txt
  js/recommendations-dashboard.js.license
  js/recommendations-dashboard.js.map
  js/recommendations-dashboard.js.map.license
  js/recommendations-main.js
  js/recommendations-main.js.LICENSE.txt
  js/recommendations-main.js.license
  js/recommendations-main.js.map
  js/recommendations-main.js.map.license
  package.json
  webpack.config.js
Labels: technical debt, 4. to release
