Repository nextcloud/recommendations, pull requests merged in 2024-08, with the labels that each got.

#749 [stable29] fix: use folder material design icon
  js/recommendations-main.js
  js/recommendations-main.js.map
  package-lock.json
  package.json
  src/components/RecommendedFile.vue
Labels: bug, 4. to release, design

#777 [master] Fix npm audit
  js/recommendations-dashboard.js
  js/recommendations-dashboard.js.license
  js/recommendations-dashboard.js.map
  js/recommendations-main.js
  js/recommendations-main.js.license
  js/recommendations-main.js.map
  package-lock.json
Labels: 3. to review, dependencies

#770 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated

#759 [stable29] Fix npm audit
  js/recommendations-main.js
  js/recommendations-main.js.map
  package-lock.json
Labels: 3. to review, dependencies

#758 [stable28] Fix npm audit
  js/recommendations-main.js
  js/recommendations-main.js.map
  package-lock.json
Labels: 3. to review, dependencies

#782 [stable30] Fix npm audit
  js/recommendations-dashboard.js
  js/recommendations-dashboard.js.license
  js/recommendations-dashboard.js.map
  js/recommendations-main.js
  js/recommendations-main.js.license
  js/recommendations-main.js.map
  package-lock.json
Labels: 3. to review, dependencies

#760 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#783 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
Labels: 3. to review, dependencies, automated
