Repository nextcloud/recommendations, pull requests merged in 2024-03, with the labels that each got.

#712 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review, dependencies, automated

#718 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#719 [stable26] Revert "fix(deps): fix npm audit"
  package-lock.json
Labels: 3. to review
