Repository nextcloud/recommendations, pull requests merged in 2024-05, with the labels that each got.

#742 Add SPDX header
  .github/workflows/reuse.yml
  .reuse/dep5
  AUTHORS.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.md
  appinfo/info.xml
  appinfo/routes.php
  js/recommendations-dashboard.js
  js/recommendations-dashboard.js.LICENSE.txt
  js/recommendations-dashboard.js.map
  js/recommendations-main.js
  js/recommendations-main.js.LICENSE.txt
  js/recommendations-main.js.map
  lib/AppInfo/Application.php
  lib/Command/GetRecommendations.php
  lib/Controller/RecommendationController.php
  lib/Controller/SettingsController.php
  lib/Dashboard/RecommendationWidget.php
  lib/Listeners/FilesLoadAdditionalScriptsListener.php
  lib/Service/FileWithComments.php
  lib/Service/IRecommendation.php
  lib/Service/IRecommendationSource.php
  lib/Service/RecentlyCommentedFilesSource.php
  lib/Service/RecentlyEditedFilesSource.php
  lib/Service/RecentlySharedFilesSource.php
  lib/Service/RecommendationService.php
  lib/Service/RecommendedFile.php
  src/components/Dashboard.vue
  src/components/Recommendations.vue
  src/components/RecommendedFile.vue
  src/components/Settings.vue
  src/dashboard.js
  src/main.js
  src/service/RecommendationService.js
  src/store/store.js
Labels: technical debt, 3. to review

#743 Add additional SPDX header
  .eslintrc.js
  .github/dependabot.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
  .github/workflows/test.yml
  .gitignore
  .l10nignore
  .php-cs-fixer.dist.php
  .reuse/dep5
  babel.config.js
  stylelint.config.js
  webpack.config.js
Labels: technical debt, 4. to release

#747 fix: use folder material design icon
  js/recommendations-dashboard.js
  js/recommendations-dashboard.js.map
  js/recommendations-main.js
  js/recommendations-main.js.map
  package-lock.json
  package.json
  src/components/RecommendedFile.vue
Labels: bug, 3. to review, design, backport-request, papercut

#750 [stable28] fix: use folder material design icon
  js/recommendations-main.js
  js/recommendations-main.js.map
  package-lock.json
  package.json
  src/components/RecommendedFile.vue
Labels: bug, 3. to review, design
